export default [
    {
        "April": [
            {
                1 : {
                    day: "FRI",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                2 : {
                    day: "SAT",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                3 : {
                    day: "SUN",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                4 : {
                    day: "MON",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                5 : {
                    day: "TUE",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                6 : {
                    day: "WED",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                7 : {
                    day: "THUR",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                8 : {
                    day: "FRI",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                9 : {
                    day: "SAT",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                10 : {
                    day: "SUN",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                11 : {
                    day: "MON",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                12 : {
                    day: "TUE",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                13 : {
                    day: "WED",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                14 : {
                    day: "THUR",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                15 : {
                    day: "FRI",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                16 : {
                    day: "SAT",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                17 : {
                    day: "SUN",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                18 : {
                    day: "MON",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                19 : {
                    day: "TUE",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                20 : {
                    day: "WED",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                21 : {
                    day: "THUR",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                22 : {
                    day: "FRI",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                23 : {
                    day: "SAT",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                24 : {
                    day: "SUN",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                25 : {
                    day: "MON",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                26 : {
                    day: "TUE",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                27 : {
                    day: "WED",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                28 : {
                    day: "THUR",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                29 : {
                    day: "FRI",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                },
                30 : {
                    day: "SAT",
                    slots : [
                        {"10:00am" : true},
                        {"10:15am" : true},
                        {"10:30am" : true},
                        {"10:45am" : true},
                        {"11:00am" : true},
                        {"11:15am" : true},
                        {"11:30am" : true},
                        {"11:45am" : true},
                        {"12:00am" : true},
                        {"12:15am" : true},
                        {"12:30am" : true},
                        {"12:45am" : true},
                        {"1:00pm" : true},
                        {"1:15pm" : true},
                        {"1:30pm" : true},
                        {"1:45pm" : true},
                        {"2:00pm" : true},
                        {"2:15pm" : true},
                        {"2:30pm" : true},
                        {"2:45pm" : true},
                        {"3:00pm" : true},
                        {"3:15pm" : true},
                        {"3:30pm" : true},
                        {"3:45pm" : true},
                        {"4:00pm" : true},
                        {"4:15pm" : true},
                        {"4:30pm" : true},
                        {"4:45pm" : true},
                        {"5:00pm" : true},
                        {"5:15pm" : true},
                        {"5:30pm" : true},
                        {"5:45pm" : true},
                        {"6:00pm" : true},
                    ]
                }
            }
        ],
        "May": [
            {
                1 : {
                    day: "SUN",
                    slots: [
                        { "10:00am": true },
                        { "10:15am": true },
                        { "10:30am": true },
                        { "10:45am": true },
                        { "11:00am": true },
                        { "11:15am": true },
                        { "11:30am": true },
                        { "11:45am": true },
                        { "12:00am": true },
                        { "12:15am": true },
                        { "12:30am": true },
                        { "12:45am": true },
                        { "1:00pm": true },
                        { "1:15pm": true },
                        { "1:30pm": true },
                        { "1:45pm": true },
                        { "2:00pm": true },
                        { "2:15pm": true },
                        { "2:30pm": true },
                        { "2:45pm": true },
                        { "3:00pm": true },
                        { "3:15pm": true },
                        { "3:30pm": true },
                        { "3:45pm": true },
                        { "4:00pm": true },
                        { "4:15pm": true },
                        { "4:30pm": true },
                        { "4:45pm": true },
                        { "5:00pm": true },
                        { "5:15pm": true },
                        { "5:30pm": true },
                        { "5:45pm": true },
                        { "6:00pm": true },
                    ]
                },
                2 : {
                    day: "MON",
                    slots: [
                        { "10:00am": true },
                        { "10:15am": true },
                        { "10:30am": true },
                        { "10:45am": true },
                        { "11:00am": true },
                        { "11:15am": true },
                        { "11:30am": true },
                        { "11:45am": true },
                        { "12:00am": true },
                        { "12:15am": true },
                        { "12:30am": true },
                        { "12:45am": true },
                        { "1:00pm": true },
                        { "1:15pm": true },
                        { "1:30pm": true },
                        { "1:45pm": true },
                        { "2:00pm": true },
                        { "2:15pm": true },
                        { "2:30pm": true },
                        { "2:45pm": true },
                        { "3:00pm": true },
                        { "3:15pm": true },
                        { "3:30pm": true },
                        { "3:45pm": true },
                        { "4:00pm": true },
                        { "4:15pm": true },
                        { "4:30pm": true },
                        { "4:45pm": true },
                        { "5:00pm": true },
                        { "5:15pm": true },
                        { "5:30pm": true },
                        { "5:45pm": true },
                        { "6:00pm": true },
                    ]
                },
                3 : {
                    day: "TUE",
                    slots: [
                        { "10:00am": true },
                        { "10:15am": true },
                        { "10:30am": true },
                        { "10:45am": true },
                        { "11:00am": true },
                        { "11:15am": true },
                        { "11:30am": true },
                        { "11:45am": true },
                        { "12:00am": true },
                        { "12:15am": true },
                        { "12:30am": true },
                        { "12:45am": true },
                        { "1:00pm": true },
                        { "1:15pm": true },
                        { "1:30pm": true },
                        { "1:45pm": true },
                        { "2:00pm": true },
                        { "2:15pm": true },
                        { "2:30pm": true },
                        { "2:45pm": true },
                        { "3:00pm": true },
                        { "3:15pm": true },
                        { "3:30pm": true },
                        { "3:45pm": true },
                        { "4:00pm": true },
                        { "4:15pm": true },
                        { "4:30pm": true },
                        { "4:45pm": true },
                        { "5:00pm": true },
                        { "5:15pm": true },
                        { "5:30pm": true },
                        { "5:45pm": true },
                        { "6:00pm": true },
                    ]
                },
                4 : {
                    day: "WED",
                    slots: [
                        { "10:00am": true },
                        { "10:15am": true },
                        { "10:30am": true },
                        { "10:45am": true },
                        { "11:00am": true },
                        { "11:15am": true },
                        { "11:30am": true },
                        { "11:45am": true },
                        { "12:00am": true },
                        { "12:15am": true },
                        { "12:30am": true },
                        { "12:45am": true },
                        { "1:00pm": true },
                        { "1:15pm": true },
                        { "1:30pm": true },
                        { "1:45pm": true },
                        { "2:00pm": true },
                        { "2:15pm": true },
                        { "2:30pm": true },
                        { "2:45pm": true },
                        { "3:00pm": true },
                        { "3:15pm": true },
                        { "3:30pm": true },
                        { "3:45pm": true },
                        { "4:00pm": true },
                        { "4:15pm": true },
                        { "4:30pm": true },
                        { "4:45pm": true },
                        { "5:00pm": true },
                        { "5:15pm": true },
                        { "5:30pm": true },
                        { "5:45pm": true },
                        { "6:00pm": true },
                    ]
                },
                5 : {
                    day: "THUR",
                    slots: [
                        { "10:00am": true },
                        { "10:15am": true },
                        { "10:30am": true },
                        { "10:45am": true },
                        { "11:00am": true },
                        { "11:15am": true },
                        { "11:30am": true },
                        { "11:45am": true },
                        { "12:00am": true },
                        { "12:15am": true },
                        { "12:30am": true },
                        { "12:45am": true },
                        { "1:00pm": true },
                        { "1:15pm": true },
                        { "1:30pm": true },
                        { "1:45pm": true },
                        { "2:00pm": true },
                        { "2:15pm": true },
                        { "2:30pm": true },
                        { "2:45pm": true },
                        { "3:00pm": true },
                        { "3:15pm": true },
                        { "3:30pm": true },
                        { "3:45pm": true },
                        { "4:00pm": true },
                        { "4:15pm": true },
                        { "4:30pm": true },
                        { "4:45pm": true },
                        { "5:00pm": true },
                        { "5:15pm": true },
                        { "5:30pm": true },
                        { "5:45pm": true },
                        { "6:00pm": true },
                    ]
                },
                6 : {
                    day: "FRI",
                    slots: [
                        { "10:00am": true },
                        { "10:15am": true },
                        { "10:30am": true },
                        { "10:45am": true },
                        { "11:00am": true },
                        { "11:15am": true },
                        { "11:30am": true },
                        { "11:45am": true },
                        { "12:00am": true },
                        { "12:15am": true },
                        { "12:30am": true },
                        { "12:45am": true },
                        { "1:00pm": true },
                        { "1:15pm": true },
                        { "1:30pm": true },
                        { "1:45pm": true },
                        { "2:00pm": true },
                        { "2:15pm": true },
                        { "2:30pm": true },
                        { "2:45pm": true },
                        { "3:00pm": true },
                        { "3:15pm": true },
                        { "3:30pm": true },
                        { "3:45pm": true },
                        { "4:00pm": true },
                        { "4:15pm": true },
                        { "4:30pm": true },
                        { "4:45pm": true },
                        { "5:00pm": true },
                        { "5:15pm": true },
                        { "5:30pm": true },
                        { "5:45pm": true },
                        { "6:00pm": true },
                    ]
                },
                7 : {
                    day: "SAT",
                    slots: [
                        { "10:00am": true },
                        { "10:15am": true },
                        { "10:30am": true },
                        { "10:45am": true },
                        { "11:00am": true },
                        { "11:15am": true },
                        { "11:30am": true },
                        { "11:45am": true },
                        { "12:00am": true },
                        { "12:15am": true },
                        { "12:30am": true },
                        { "12:45am": true },
                        { "1:00pm": true },
                        { "1:15pm": true },
                        { "1:30pm": true },
                        { "1:45pm": true },
                        { "2:00pm": true },
                        { "2:15pm": true },
                        { "2:30pm": true },
                        { "2:45pm": true },
                        { "3:00pm": true },
                        { "3:15pm": true },
                        { "3:30pm": true },
                        { "3:45pm": true },
                        { "4:00pm": true },
                        { "4:15pm": true },
                        { "4:30pm": true },
                        { "4:45pm": true },
                        { "5:00pm": true },
                        { "5:15pm": true },
                        { "5:30pm": true },
                        { "5:45pm": true },
                        { "6:00pm": true },
                    ]
                }, 
            }           
        ]
    },
]